package com.example.matchandplay;

import android.content.Intent;
import android.os.Bundle;
import android.util.Patterns;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;

import com.google.android.gms.auth.api.signin.GoogleSignIn;
import com.google.android.gms.auth.api.signin.GoogleSignInAccount;
import com.google.android.gms.auth.api.signin.GoogleSignInClient;
import com.google.android.gms.auth.api.signin.GoogleSignInOptions;
import com.google.android.gms.common.api.ApiException;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.AuthCredential;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import com.google.firebase.auth.GoogleAuthProvider;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

public class LoginActivity extends AppCompatActivity {

    private Button mLogin, mGoogleLogin;
    private EditText mEmail, mPassword;
    private TextView mRegister;
    private FirebaseAuth mAuth;
    private GoogleSignInClient mGoogleSignInClient;
    private static final int RC_SIGN_IN = 123;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        mAuth = FirebaseAuth.getInstance();

        // 1. Check if user is already logged in (Auto-Login)
        if (mAuth.getCurrentUser() != null) {
            startActivity(new Intent(LoginActivity.this, MainActivity.class));
            finish();
        }

        // 2. Configure Google Sign In
        GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id)) // Auto-generated by Firebase
                .requestEmail()
                .build();
        mGoogleSignInClient = GoogleSignIn.getClient(this, gso);

        // 3. Connect UI Elements
        mLogin = findViewById(R.id.btnLogin);
        mGoogleLogin = findViewById(R.id.btnGoogle);
        mEmail = findViewById(R.id.inputEmail);
        mPassword = findViewById(R.id.inputPassword);
        mRegister = findViewById(R.id.txtGoToRegister);

        // 4. Standard Email Login Logic (WITH EMAIL FORMAT CHECK)
        mLogin.setOnClickListener(v -> {
            String email = mEmail.getText().toString().trim();
            String password = mPassword.getText().toString().trim();

            // --- 1. Client-Side Checks ---
            if (email.isEmpty()) {
                mEmail.setError("Email is required");
                mEmail.requestFocus(); // Moves the blinking cursor here
                return;
            }

            // Check if it actually looks like an email address
            if (!Patterns.EMAIL_ADDRESS.matcher(email).matches()) {
                mEmail.setError("Please enter a valid email address");
                mEmail.requestFocus();
                return;
            }

            if (password.isEmpty()) {
                mPassword.setError("Password is required");
                mPassword.requestFocus();
                return;
            }

            // --- 2. Firebase Server Checks ---
            mAuth.signInWithEmailAndPassword(email, password).addOnCompleteListener(LoginActivity.this, task -> {
                if (!task.isSuccessful()) {
                    // Find out EXACTLY what went wrong
                    try {
                        throw task.getException();
                    } catch (com.google.firebase.auth.FirebaseAuthInvalidUserException e) {
                        mEmail.setError("No account found with this email");
                        mEmail.requestFocus();
                    } catch (com.google.firebase.auth.FirebaseAuthInvalidCredentialsException e) {
                        // We already know the email format is good, so it must be the password!
                        mPassword.setError("Incorrect password");
                        mPassword.requestFocus();
                    } catch (Exception e) {
                        // Fallback for network errors, etc.
                        Toast.makeText(LoginActivity.this, "Login Failed: " + e.getMessage(), Toast.LENGTH_LONG).show();
                    }
                } else {
                    // Login successful -> Go to Main App
                    Intent intent = new Intent(LoginActivity.this, MainActivity.class);
                    startActivity(intent);
                    finish();
                }
            });
        });

        // 5. Google Login Button Logic
        mGoogleLogin.setOnClickListener(v -> signInWithGoogle());

        // 6. Go to Register Page
        mRegister.setOnClickListener(v -> {
            Intent intent = new Intent(LoginActivity.this, RegisterActivity.class);
            startActivity(intent);
            finish();
        });
    }

    // --- GOOGLE SIGN IN METHODS ---

    private void signInWithGoogle() {
        Intent signInIntent = mGoogleSignInClient.getSignInIntent();
        startActivityForResult(signInIntent, RC_SIGN_IN);
    }

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == RC_SIGN_IN) {
            Task<GoogleSignInAccount> task = GoogleSignIn.getSignedInAccountFromIntent(data);
            try {
                // Google Sign In was successful, authenticate with Firebase
                GoogleSignInAccount account = task.getResult(ApiException.class);
                firebaseAuthWithGoogle(account.getIdToken());
            } catch (ApiException e) {
                // Google Sign In failed
                Toast.makeText(this, "Google Sign In Failed: " + e.getMessage(), Toast.LENGTH_SHORT).show();
            }
        }
    }

    private void firebaseAuthWithGoogle(String idToken) {
        AuthCredential credential = GoogleAuthProvider.getCredential(idToken, null);
        mAuth.signInWithCredential(credential)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            // Sign in success, now check if they are new or old
                            FirebaseUser user = mAuth.getCurrentUser();
                            checkUserExists(user.getUid());
                        } else {
                            Toast.makeText(LoginActivity.this, "Authentication Failed.", Toast.LENGTH_SHORT).show();
                        }
                    }
                });
    }

    // --- CRITICAL: THE ROUTING LOGIC ---
    private void checkUserExists(String userId) {
        DatabaseReference userDb = FirebaseDatabase.getInstance().getReference().child("Users");

        userDb.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                if (snapshot.child("player").hasChild(userId)) {
                    // User exists as a Player. Check if they finished setup!
                    Boolean isSetup = false;
                    if (snapshot.child("player").child(userId).hasChild("profileSetup")) {
                        isSetup = (Boolean) snapshot.child("player").child(userId).child("profileSetup").getValue();
                    }

                    if (isSetup != null && isSetup) {
                        startActivity(new Intent(LoginActivity.this, MainActivity.class));
                    } else {
                        // Profile not finished -> Go to Player Profile Page
                        startActivity(new Intent(LoginActivity.this, ProfileActivity.class));
                    }
                    finish();

                } else if (snapshot.child("team").hasChild(userId)) {
                    // User exists as a Team. Check if they finished setup!
                    Boolean isSetup = false;
                    if (snapshot.child("team").child(userId).hasChild("profileSetup")) {
                        isSetup = (Boolean) snapshot.child("team").child(userId).child("profileSetup").getValue();
                    }

                    if (isSetup != null && isSetup) {
                        startActivity(new Intent(LoginActivity.this, MainActivity.class));
                    } else {
                        // Profile not finished -> Go to Team Profile Page
                        startActivity(new Intent(LoginActivity.this, TeamProfileActivity.class));
                    }
                    finish();

                } else {
                    // User is BRAND NEW (Google Login) -> Ask "Who are you?"
                    startActivity(new Intent(LoginActivity.this, ChooseTypeActivity.class));
                    finish();
                }
            }

            @Override
            public void onCancelled(@NonNull DatabaseError error) {}
        });
    }
}